[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.13.3"

[[build.processing]]
  for = "requirements.txt"
  command = "apt-get update && apt-get install -y ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 